# Site settings
title: 章鱼健康
email: jetfox2022@foxmail.com
description: > # this means to ignore newlines until "baseurl:"
baseurl: "" # the subpath of your site, e.g. /blog/
url: "" # the base hostname & protocol for your site
#网站 ICON （要求为 PNG 格式）
favicon : 'img\logosmallround.png'

twitter_username:
github_username:

# Build settings
markdown: kramdown
